[pytest]
django_find_project = false
pythonpath = ./tests/demoapp/
DJANGO_SETTINGS_MODULE = demo.settings
norecursedirs = demo,.tox
addopts =
      --tb=short
      --capture=no
      --echo-version=django
      --echo-attr=django.conf.settings.DATABASES.default.ENGINE
      --cov=strategy_field
      --cov-report=html
      --cov-report=xml
      --cov-config=tests/.coveragerc

python_files =
    tests/test_*.py
    tests/**/test_*.py
    src/*.py

markers =
    functional: mark a test as functional
    selenium: selenium test
    skip: skip test
